/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerSanPham;
import Model.ModelSanPham;
import static View.Banhang.BH;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Computer
 */
public class ChuyenBan extends javax.swing.JFrame {

    DefaultComboBoxModel modellist;
    String mabancu = "", mabanmoi = "", masp = "", tensp = "";
    int soluong = 0;

    /**
     * Creates new form ChuyenBan
     */
    public ChuyenBan() {
        setLocationRelativeTo(null);
        initComponents();
        setTitle("CHUYỂN BÀN");
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbmabancu = new javax.swing.JLabel();
        btnchuyen = new javax.swing.JButton();
        cblist = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btndongcb = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BẠN MUỐN CHUYỂN BÀN?");

        jLabel2.setText("Bàn hiện tại:");

        lbmabancu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbmabancu.setForeground(new java.awt.Color(204, 0, 51));

        btnchuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/horizontal.png"))); // NOI18N
        btnchuyen.setText("Chuyển bàn");
        btnchuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchuyenActionPerformed(evt);
            }
        });

        cblist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn bàn..." }));
        cblist.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cblistAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cblist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblistActionPerformed(evt);
            }
        });

        btndongcb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancel.png"))); // NOI18N
        btndongcb.setText("Đóng");
        btndongcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndongcbActionPerformed(evt);
            }
        });

        jLabel3.setText("Chuyển sang bàn:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnchuyen)
                                .addGap(18, 18, 18)
                                .addComponent(btndongcb, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cblist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbmabancu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 11, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbmabancu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cblist, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnchuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndongcb))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cblistAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cblistAncestorAdded

        ModelSanPham sp = new ModelSanPham();
        List<ModelSanPham> ds = sp.getdsBan();
        modellist = new DefaultComboBoxModel<>();
        for (int i = 0; i < ds.size(); i++) {

            modellist.addElement(ds.get(i).getMaban());

        }
        cblist.setModel(modellist);


    }//GEN-LAST:event_cblistAncestorAdded

    private void btnchuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchuyenActionPerformed
        ControllerSanPham csanpham = new ControllerSanPham();
        mabancu = lbmabancu.getText();
        mabanmoi = modellist.getSelectedItem().toString();
        ModelSanPham sp = new ModelSanPham();
        ModelSanPham ds = sp.laymagoi(mabancu, masp);
        int magoi = ds.getMagoi();
        boolean result = csanpham.chuyenban(masp, mabancu, mabanmoi, magoi);
//        JOptionPane.showMessageDialog(null, mabancu + mabanmoi + soluong + masp);
        if (result) {
            JOptionPane.showMessageDialog(null, "Chuyển bàn thành công!");
            
            // Refresh Panel
            Banhang bh=new Banhang();
            BH.panelban.removeAll();
            BH.loadiconBan();
            BH.panelban.repaint();
            BH.panelban.revalidate();
            
            dispose();
            //-------------
        }
    }//GEN-LAST:event_btnchuyenActionPerformed

    private void btndongcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndongcbActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_btndongcbActionPerformed

    private void cblistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cblistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChuyenBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChuyenBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChuyenBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChuyenBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChuyenBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchuyen;
    private javax.swing.JButton btndongcb;
    private javax.swing.JComboBox<String> cblist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel lbmabancu;
    // End of variables declaration//GEN-END:variables

}
