/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerKho;
import Controller.ControllerSanPham;
import Model.ModelKho;
import Model.ModelSanPham;
import Model.ThongKe;
import static View.Banhang.BH;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Computer
 */
public class ThanhToan extends javax.swing.JFrame {

    public String masp = "", maban = "";
    public int soluong = 0;
    public ArrayList<ThongKe> ds = new ThongKe().getTk();

    /**
     * Creates new form ThanhToan
     */
    public ThanhToan() {
        initComponents();
        setTitle("XÁC NHẬN THANH TOÁN");
//        JOptionPane.showMessageDialog(null,maban);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbicon = new javax.swing.JLabel();
        lbmaban = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbtongtien = new javax.swing.JLabel();
        btnthanhtoantien = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbtienkhach = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbtienthoi = new javax.swing.JLabel();
        btnhoadon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setForeground(java.awt.Color.green);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("BẠN CÓ MUỐN THANH TOÁN KHÔNG?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 0, 354, 48));

        lbicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/table.png"))); // NOI18N
        getContentPane().add(lbicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 59, 68, 62));

        lbmaban.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbmaban.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lbmaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 54, 95, 24));

        jLabel2.setText("Tổng tiền:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 93, 54, 28));

        lbtongtien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbtongtien.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lbtongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 93, 97, 28));

        btnthanhtoantien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/checkmark.png"))); // NOI18N
        btnthanhtoantien.setText("Chấp nhận");
        btnthanhtoantien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthanhtoantienActionPerformed(evt);
            }
        });
        getContentPane().add(btnthanhtoantien, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 120, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancel.png"))); // NOI18N
        jButton1.setText("Hủy bỏ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 121, 50));

        jLabel3.setText("Tiền khách đưa:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 136, -1, 23));
        getContentPane().add(lbtienkhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 136, 93, 25));

        jLabel4.setText("Tiền thối lại:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 181, 73, 26));

        lbtienthoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbtienthoi.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(lbtienthoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 181, 93, 25));

        btnhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/invoice.png"))); // NOI18N
        btnhoadon.setText("Hóa đơn");
        btnhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhoadonActionPerformed(evt);
            }
        });
        getContentPane().add(btnhoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 121, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Refresh Panel
        Banhang bh = new Banhang();
        BH.panelban.removeAll();
        BH.loadiconBan();
        BH.panelban.repaint();
        BH.panelban.revalidate();
        dispose();
        //-------------


    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnthanhtoantienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthanhtoantienActionPerformed
        boolean result = false;
        boolean resultsp1 = false, resultsp2 = false, resultkho = false;
        ControllerSanPham csanpham;
        ControllerKho kho;
        ModelKho modelkho = null;
        for (int i = 0; i < ds.size(); i++) {
            kho = new ControllerKho();
            modelkho = new ModelKho();
            String masp = ds.get(i).getMasp();
            //Kiem tra soluong thuc te trong kho
            int soluongtrongkho = 0;
            int soluongupdate =0;
            int slcf = 0, slsua = 0, sllip =0;
            int soluongsudung = ds.get(i).getSoluong();
            // Cap nhat lai so luong trong kho
            
            ModelKho sp = new ModelKho();
            switch (masp) {
                case "cfsua":
                    slcf = sp.laysoluong("cf").getSoluong() - soluongsudung;
                    slsua = sp.laysoluong("sua").getSoluong() - soluongsudung;
                    resultsp1 = kho.capnhatsoluong1sp("cf", slcf);
                    resultsp2 = kho.capnhatsoluong1sp("sua", slsua);
                    break;
                case "lipsua":
                    sllip = sp.laysoluong("lip").getSoluong() - soluongsudung;
                    slsua = sp.laysoluong("sua").getSoluong() - soluongsudung;
                    resultsp1 = kho.capnhatsoluong1sp("lip", slcf);
                    resultsp2 = kho.capnhatsoluong1sp("sua", slsua);
                    break;
                default:
                    soluongtrongkho = sp.laysoluong(masp).getSoluong();
                    soluongupdate = soluongtrongkho - soluongsudung;
                    resultkho = kho.capnhatsoluong1sp(masp, soluongupdate);
                    break;
            }

            Date date = new Date(System.currentTimeMillis());
            SimpleDateFormat formatngay = new SimpleDateFormat("dd/MM/yyyy");
            String ngayht = formatngay.format(date);
            ThongKe tk = new ThongKe();
            result = tk.capnhatsoluong(masp, soluongsudung, ngayht);

//            JOptionPane.showMessageDialog(this,ds.get(i).getMasp());
        }
        if (result || resultkho) {
            ModelSanPham sp = new ModelSanPham();
            csanpham = new ControllerSanPham();
            boolean rs = sp.xoasp(maban);
            JOptionPane.showMessageDialog(this, "Thanh toán thành công!");
            // Refresh Panel
            BH.panelban.removeAll();
            BH.loadiconBan();
            BH.panelban.repaint();
            BH.panelban.revalidate();
            csanpham.loadTableBan(BH.tableBan, maban);
            BH.txtthanhtien.setText("");
            BH.txttienkhach.setText("");
            dispose();
            //-------------
        }
    }//GEN-LAST:event_btnthanhtoantienActionPerformed

    private void btnhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhoadonActionPerformed
        try {
            HoaDon hd = new HoaDon();
            hd.setVisible(true);
            hd.setLocation(450, 60);
            Date date = new Date(System.currentTimeMillis());
            SimpleDateFormat formatngay = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat formatgio = new SimpleDateFormat("hh:mm:ss");
            String ngayht = formatngay.format(date);
            String gioht = formatgio.format(date);
            hd.lbdate.setText(ngayht);
            hd.lbgio.setText(gioht);
            hd.lbtongtien.setText(lbtongtien.getText());
            hd.lbkhach.setText(lbtienkhach.getText());
            hd.lbtienthoi.setText(lbtienthoi.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnhoadonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThanhToan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhoadon;
    private javax.swing.JButton btnthanhtoantien;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbicon;
    public javax.swing.JLabel lbmaban;
    public javax.swing.JLabel lbtienkhach;
    public javax.swing.JLabel lbtienthoi;
    public javax.swing.JLabel lbtongtien;
    // End of variables declaration//GEN-END:variables
}
